GEMINI_API_KEY = "AIzaSyBIG-t52MQqMJn-v0ad5QRW85p7ZJLEa5U"
EMAIL_SENDER = "suryatesting40@gmail.com"
EMAIL_PASSWORD = "Test@123"
SUPABASE_URL = "https://roxxafpiqpgfnjyernow.supabase.co"
SUPABASE_KEY = "sb_publishable_Paxtsz0xiccPapddiQRDUA_KE3DMf0h"
SENDGRID_API_KEY = "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"
SENDGRID_FROM_EMAIL = "suryatesting40@gmail.com"
